spring.application.name=agro-backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/agro_backend
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
